[package]
name = "keto_recipes_api"
version = "0.1.0"
edition = "2021"
rust-version = "1.68"

[dependencies]
axum = "0.6.11"
serde = { version = "1.0.155", features = ["derive"] }
tokio = { version = "1.26.0", features = ["full"] }
tracing = "0.1.37"
tracing-subscriber = "0.3.16"
