# yamllint disable rule:document-start rule:line-length

# Kan man bryta ut en variabel här?

steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "--target",
        "builder",
        "-t",
        "test-image",
        ".",
      ]
  - name: 'gcr.io/cloud-builders/docker'
    # Run tests in release mode to reuse the compilation done by the build target anyway.
    args: ['run', 'test-image', 'cargo', 'test', '--release', '--target', 'x86_64-unknown-linux-gnu']

  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "--target",
        "production",
        "-t",
        "europe-north1-docker.pkg.dev/keto-recipes-380514/keto-recipes-api/keto-recipes-api:$SHORT_SHA",
        ".",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "europe-north1-docker.pkg.dev/keto-recipes-380514/keto-recipes-api/keto-recipes-api:$SHORT_SHA",
      ]
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "deploy",
        "keto-recipes-api",
        "--image",
        "europe-north1-docker.pkg.dev/keto-recipes-380514/keto-recipes-api/keto-recipes-api:$SHORT_SHA",
        "--region",
        "europe-north1",
        "--allow-unauthenticated",
      ]
images:
  [
    "europe-north1-docker.pkg.dev/keto-recipes-380514/keto-recipes-api/keto-recipes-api:$SHORT_SHA",
  ]

options:
  machineType: "E2_HIGHCPU_8"
